// ─── CFOP ─────────────────────────────────────────────────────────────────────
// dir: "E" = Entrada  |  "S" = Saída
// escopo: "est" = Estadual  |  "int" = Interestadual  |  "ext" = Exterior
// grupo: categoria principal

export const CFOP_DATA = [
  // ── ENTRADAS ESTADUAIS ─────────────────────────────────────────────────────
  { codigo:"1.101", dir:"E", escopo:"est", grupo:"Compras – Industrialização",   desc:"Compra para industrialização" },
  { codigo:"1.102", dir:"E", escopo:"est", grupo:"Compras – Comercialização",    desc:"Compra para comercialização" },
  { codigo:"1.116", dir:"E", escopo:"est", grupo:"Compras – Industrialização",   desc:"Compra para industrialização originada de encomenda para recebimento futuro" },
  { codigo:"1.118", dir:"E", escopo:"est", grupo:"Compras – Subst. Tributária",  desc:"Compra de mercadoria para industrialização – sujeita a ST" },
  { codigo:"1.121", dir:"E", escopo:"est", grupo:"Compras – Industrialização",   desc:"Compra para industrialização sob regime de industrialização por encomenda" },
  { codigo:"1.122", dir:"E", escopo:"est", grupo:"Compras – Comercialização",    desc:"Compra para comercialização de mercadoria em consignação mercantil" },
  { codigo:"1.126", dir:"E", escopo:"est", grupo:"Compras – Serviços",           desc:"Compra para utilização na prestação de serviço sujeita ao ICMS" },
  { codigo:"1.201", dir:"E", escopo:"est", grupo:"Devoluções",                   desc:"Devolução de venda de produção do estabelecimento" },
  { codigo:"1.202", dir:"E", escopo:"est", grupo:"Devoluções",                   desc:"Devolução de venda de mercadoria adquirida para comercialização" },
  { codigo:"1.301", dir:"E", escopo:"est", grupo:"Uso e Consumo",                desc:"Compras para uso e consumo" },
  { codigo:"1.352", dir:"E", escopo:"est", grupo:"Energia Elétrica",             desc:"Compra de energia elétrica por estabelecimento industrial" },
  { codigo:"1.353", dir:"E", escopo:"est", grupo:"Energia Elétrica",             desc:"Compra de energia elétrica por estabelecimento comercial" },
  { codigo:"1.354", dir:"E", escopo:"est", grupo:"Energia Elétrica",             desc:"Compra de energia elétrica consumida em iluminação de vias públicas" },
  { codigo:"1.355", dir:"E", escopo:"est", grupo:"Energia Elétrica",             desc:"Compra de energia elétrica para distribuição" },
  { codigo:"1.401", dir:"E", escopo:"est", grupo:"Compras – Subst. Tributária",  desc:"Compra para industrialização em operação com mercadoria sujeita a ST" },
  { codigo:"1.403", dir:"E", escopo:"est", grupo:"Compras – Subst. Tributária",  desc:"Compra de mercadoria para comercialização – sujeita a ST" },
  { codigo:"1.407", dir:"E", escopo:"est", grupo:"Compras – Subst. Tributária",  desc:"Compra de mercadoria para uso e consumo – sujeita a ST" },
  { codigo:"1.411", dir:"E", escopo:"est", grupo:"Devoluções",                   desc:"Devolução de venda de produção – sujeita a ST" },
  { codigo:"1.412", dir:"E", escopo:"est", grupo:"Devoluções",                   desc:"Devolução de venda de mercadoria adquirida – sujeita a ST" },
  { codigo:"1.551", dir:"E", escopo:"est", grupo:"Ativo Imobilizado",            desc:"Compra de bem para o ativo imobilizado" },
  { codigo:"1.556", dir:"E", escopo:"est", grupo:"Ativo Imobilizado",            desc:"Compra de material para uso ou consumo – imobilizado" },
  { codigo:"1.603", dir:"E", escopo:"est", grupo:"Ressarcimento ST",             desc:"Ressarcimento de ICMS retido por substituição tributária" },
  { codigo:"1.901", dir:"E", escopo:"est", grupo:"Industrialização Encomenda",   desc:"Entrada para industrialização por encomenda" },
  { codigo:"1.903", dir:"E", escopo:"est", grupo:"Demonstração / Consignação",   desc:"Entrada de mercadoria recebida para demonstração" },
  { codigo:"1.904", dir:"E", escopo:"est", grupo:"Venda Fora do Estabelecimento",desc:"Retorno de remessa para venda fora do estabelecimento" },
  { codigo:"1.905", dir:"E", escopo:"est", grupo:"Demonstração / Consignação",   desc:"Entrada de mercadoria recebida em consignação mercantil" },

  // ── ENTRADAS INTERESTADUAIS ────────────────────────────────────────────────
  { codigo:"2.101", dir:"E", escopo:"int", grupo:"Compras – Industrialização",   desc:"Compra para industrialização" },
  { codigo:"2.102", dir:"E", escopo:"int", grupo:"Compras – Comercialização",    desc:"Compra para comercialização" },
  { codigo:"2.116", dir:"E", escopo:"int", grupo:"Compras – Industrialização",   desc:"Compra para industrialização originada de encomenda para recebimento futuro" },
  { codigo:"2.118", dir:"E", escopo:"int", grupo:"Compras – Subst. Tributária",  desc:"Compra de mercadoria para industrialização – sujeita a ST" },
  { codigo:"2.201", dir:"E", escopo:"int", grupo:"Devoluções",                   desc:"Devolução de venda de produção do estabelecimento" },
  { codigo:"2.202", dir:"E", escopo:"int", grupo:"Devoluções",                   desc:"Devolução de venda de mercadoria adquirida para comercialização" },
  { codigo:"2.301", dir:"E", escopo:"int", grupo:"Uso e Consumo",                desc:"Compras para uso e consumo" },
  { codigo:"2.352", dir:"E", escopo:"int", grupo:"Energia Elétrica",             desc:"Compra de energia elétrica por estabelecimento industrial" },
  { codigo:"2.353", dir:"E", escopo:"int", grupo:"Energia Elétrica",             desc:"Compra de energia elétrica por estabelecimento comercial" },
  { codigo:"2.401", dir:"E", escopo:"int", grupo:"Compras – Subst. Tributária",  desc:"Compra para industrialização em operação com mercadoria sujeita a ST" },
  { codigo:"2.403", dir:"E", escopo:"int", grupo:"Compras – Subst. Tributária",  desc:"Compra de mercadoria para comercialização – sujeita a ST" },
  { codigo:"2.407", dir:"E", escopo:"int", grupo:"Compras – Subst. Tributária",  desc:"Compra de mercadoria para uso e consumo – sujeita a ST" },
  { codigo:"2.551", dir:"E", escopo:"int", grupo:"Ativo Imobilizado",            desc:"Compra de bem para o ativo imobilizado" },
  { codigo:"2.603", dir:"E", escopo:"int", grupo:"Ressarcimento ST",             desc:"Ressarcimento de ICMS retido por substituição tributária" },
  { codigo:"2.901", dir:"E", escopo:"int", grupo:"Industrialização Encomenda",   desc:"Entrada para industrialização por encomenda" },
  { codigo:"2.903", dir:"E", escopo:"int", grupo:"Demonstração / Consignação",   desc:"Entrada de mercadoria recebida para demonstração" },
  { codigo:"2.904", dir:"E", escopo:"int", grupo:"Venda Fora do Estabelecimento",desc:"Retorno de remessa para venda fora do estabelecimento" },
  { codigo:"2.905", dir:"E", escopo:"int", grupo:"Demonstração / Consignação",   desc:"Entrada de mercadoria recebida em consignação mercantil" },

  // ── ENTRADAS DO EXTERIOR ───────────────────────────────────────────────────
  { codigo:"3.101", dir:"E", escopo:"ext", grupo:"Importação – Industrialização",desc:"Compra para industrialização" },
  { codigo:"3.102", dir:"E", escopo:"ext", grupo:"Importação – Comercialização", desc:"Compra para comercialização" },
  { codigo:"3.126", dir:"E", escopo:"ext", grupo:"Importação – Serviços",        desc:"Compra para utilização na prestação de serviço" },
  { codigo:"3.127", dir:"E", escopo:"ext", grupo:"Importação – Uso e Consumo",   desc:"Compra para utilização em consumo na prestação de serviço de transporte" },
  { codigo:"3.301", dir:"E", escopo:"ext", grupo:"Importação – Uso e Consumo",   desc:"Compra para uso e consumo" },
  { codigo:"3.551", dir:"E", escopo:"ext", grupo:"Importação – Ativo Imobilizado",desc:"Compra de bem para o ativo imobilizado" },

  // ── SAÍDAS ESTADUAIS ───────────────────────────────────────────────────────
  { codigo:"5.101", dir:"S", escopo:"est", grupo:"Vendas – Produção Própria",    desc:"Venda de produção do estabelecimento" },
  { codigo:"5.102", dir:"S", escopo:"est", grupo:"Vendas – Comercialização",     desc:"Venda de mercadoria adquirida para comercialização" },
  { codigo:"5.103", dir:"S", escopo:"est", grupo:"Vendas – Subst. Tributária",   desc:"Venda de produção do estabelecimento – sujeita a ST" },
  { codigo:"5.104", dir:"S", escopo:"est", grupo:"Vendas – Subst. Tributária",   desc:"Venda de mercadoria adquirida – sujeita a ST" },
  { codigo:"5.109", dir:"S", escopo:"est", grupo:"Vendas – Zona Franca",         desc:"Venda de produção do estabelecimento destinada à Zona Franca de Manaus" },
  { codigo:"5.110", dir:"S", escopo:"est", grupo:"Vendas – Zona Franca",         desc:"Venda de mercadoria adquirida destinada à Zona Franca de Manaus" },
  { codigo:"5.116", dir:"S", escopo:"est", grupo:"Vendas – Venda à Ordem",       desc:"Venda de produção do estabelecimento originada de encomenda para entrega futura" },
  { codigo:"5.117", dir:"S", escopo:"est", grupo:"Vendas – Venda à Ordem",       desc:"Venda de mercadoria adquirida – entrega ao destinatário remetente" },
  { codigo:"5.118", dir:"S", escopo:"est", grupo:"Vendas – Venda à Ordem",       desc:"Venda de produção entregue ao destinatário pelo fornecedor" },
  { codigo:"5.119", dir:"S", escopo:"est", grupo:"Vendas – Venda à Ordem",       desc:"Venda de mercadoria entregue ao destinatário pelo fornecedor" },
  { codigo:"5.122", dir:"S", escopo:"est", grupo:"Vendas – Drawback",            desc:"Venda de produção do estabelecimento – regime de drawback" },
  { codigo:"5.151", dir:"S", escopo:"est", grupo:"Transferências",               desc:"Transferência de produção entre estabelecimentos da mesma empresa" },
  { codigo:"5.152", dir:"S", escopo:"est", grupo:"Transferências",               desc:"Transferência de mercadoria entre estabelecimentos da mesma empresa" },
  { codigo:"5.155", dir:"S", escopo:"est", grupo:"Transferências",               desc:"Transferência de produção – sujeita a ST" },
  { codigo:"5.156", dir:"S", escopo:"est", grupo:"Transferências",               desc:"Transferência de mercadoria – sujeita a ST" },
  { codigo:"5.201", dir:"S", escopo:"est", grupo:"Devoluções",                   desc:"Devolução de compra para industrialização" },
  { codigo:"5.202", dir:"S", escopo:"est", grupo:"Devoluções",                   desc:"Devolução de compra para comercialização" },
  { codigo:"5.205", dir:"S", escopo:"est", grupo:"Devoluções",                   desc:"Anulação de valor relativo à aquisição de serviço de comunicação" },
  { codigo:"5.207", dir:"S", escopo:"est", grupo:"Devoluções",                   desc:"Anulação de valor relativo à aquisição de serviço de transporte" },
  { codigo:"5.208", dir:"S", escopo:"est", grupo:"Devoluções",                   desc:"Devolução de mercadoria recebida em transferência" },
  { codigo:"5.210", dir:"S", escopo:"est", grupo:"Devoluções",                   desc:"Devolução de compras para utilização na prestação de serviço" },
  { codigo:"5.251", dir:"S", escopo:"est", grupo:"Energia Elétrica",             desc:"Venda de energia elétrica para estabelecimento industrial" },
  { codigo:"5.252", dir:"S", escopo:"est", grupo:"Energia Elétrica",             desc:"Venda de energia elétrica para estabelecimento comercial" },
  { codigo:"5.253", dir:"S", escopo:"est", grupo:"Energia Elétrica",             desc:"Venda de energia elétrica para estabelecimento prestador de serviço de transporte" },
  { codigo:"5.301", dir:"S", escopo:"est", grupo:"Serviços",                     desc:"Prestação de serviço de comunicação para execução de serviço da mesma natureza" },
  { codigo:"5.302", dir:"S", escopo:"est", grupo:"Serviços",                     desc:"Prestação de serviço de comunicação a assinante ou destinatário não contribuinte" },
  { codigo:"5.401", dir:"S", escopo:"est", grupo:"Vendas – Subst. Tributária",   desc:"Venda de produção do estabelecimento – ST retida pelo remetente" },
  { codigo:"5.402", dir:"S", escopo:"est", grupo:"Vendas – Subst. Tributária",   desc:"Venda de produção do estabelecimento – ST retida anteriormente" },
  { codigo:"5.403", dir:"S", escopo:"est", grupo:"Vendas – Subst. Tributária",   desc:"Venda de mercadoria adquirida com ST já retida" },
  { codigo:"5.405", dir:"S", escopo:"est", grupo:"Vendas – Subst. Tributária",   desc:"Venda de mercadoria adquirida com ST a não contribuinte (consumidor final)" },
  { codigo:"5.408", dir:"S", escopo:"est", grupo:"Vendas – Subst. Tributária",   desc:"Transferência de mercadoria adquirida com ST retida anteriormente" },
  { codigo:"5.409", dir:"S", escopo:"est", grupo:"Vendas – Subst. Tributária",   desc:"Devolução de compra de mercadoria com ST retida anteriormente" },
  { codigo:"5.501", dir:"S", escopo:"est", grupo:"Depósito Fechado / Armazém",   desc:"Remessa de produção do estabelecimento para depósito fechado" },
  { codigo:"5.502", dir:"S", escopo:"est", grupo:"Depósito Fechado / Armazém",   desc:"Remessa de mercadoria para depósito fechado" },
  { codigo:"5.503", dir:"S", escopo:"est", grupo:"Depósito Fechado / Armazém",   desc:"Retorno de mercadoria de depósito fechado" },
  { codigo:"5.551", dir:"S", escopo:"est", grupo:"Ativo Imobilizado",            desc:"Venda de bem do ativo imobilizado" },
  { codigo:"5.552", dir:"S", escopo:"est", grupo:"Ativo Imobilizado",            desc:"Transferência de bem do ativo imobilizado" },
  { codigo:"5.555", dir:"S", escopo:"est", grupo:"Brindes / Amostras",           desc:"Remessa de amostra grátis" },
  { codigo:"5.556", dir:"S", escopo:"est", grupo:"Brindes / Amostras",           desc:"Remessa de mercadoria em doação" },
  { codigo:"5.602", dir:"S", escopo:"est", grupo:"Crédito ST",                   desc:"Transferência de saldo credor de ST para outro estabelecimento" },
  { codigo:"5.605", dir:"S", escopo:"est", grupo:"Crédito ST",                   desc:"Transferência de saldo credor de ICMS acumulado para outro estabelecimento" },
  { codigo:"5.900", dir:"S", escopo:"est", grupo:"Outras",                       desc:"Outras saídas de mercadoria ou prestações de serviço não especificadas" },
  { codigo:"5.906", dir:"S", escopo:"est", grupo:"Outras",                       desc:"Remessa de mercadoria para armazém geral" },
  { codigo:"5.907", dir:"S", escopo:"est", grupo:"Outras",                       desc:"Retorno simbólico de mercadoria depositada em armazém geral" },
  { codigo:"5.929", dir:"S", escopo:"est", grupo:"Outras",                       desc:"Lançamento de emissão de NF para operação também registrada em ECF" },
  { codigo:"5.933", dir:"S", escopo:"est", grupo:"Serviços – ISS",               desc:"Prestação de serviço tributado pelo ISSQN" },
  { codigo:"5.949", dir:"S", escopo:"est", grupo:"Outras",                       desc:"Outra saída de mercadoria ou prestação de serviço não especificada" },

  // ── SAÍDAS INTERESTADUAIS ──────────────────────────────────────────────────
  { codigo:"6.101", dir:"S", escopo:"int", grupo:"Vendas – Produção Própria",    desc:"Venda de produção do estabelecimento" },
  { codigo:"6.102", dir:"S", escopo:"int", grupo:"Vendas – Comercialização",     desc:"Venda de mercadoria adquirida para comercialização" },
  { codigo:"6.103", dir:"S", escopo:"int", grupo:"Vendas – Subst. Tributária",   desc:"Venda de produção do estabelecimento – sujeita a ST" },
  { codigo:"6.104", dir:"S", escopo:"int", grupo:"Vendas – Subst. Tributária",   desc:"Venda de mercadoria adquirida – sujeita a ST" },
  { codigo:"6.107", dir:"S", escopo:"int", grupo:"Vendas – Zona Franca",         desc:"Venda de produção do estabelecimento destinada a ZFM – benefício fiscal" },
  { codigo:"6.108", dir:"S", escopo:"int", grupo:"Vendas – Zona Franca",         desc:"Venda de mercadoria adquirida destinada a ZFM – benefício fiscal" },
  { codigo:"6.109", dir:"S", escopo:"int", grupo:"Vendas – Zona Franca",         desc:"Venda de produção destinada à Zona Franca de Manaus" },
  { codigo:"6.110", dir:"S", escopo:"int", grupo:"Vendas – Zona Franca",         desc:"Venda de mercadoria adquirida destinada à Zona Franca de Manaus" },
  { codigo:"6.116", dir:"S", escopo:"int", grupo:"Vendas – Venda à Ordem",       desc:"Venda de produção do estabelecimento originada de encomenda para entrega futura" },
  { codigo:"6.117", dir:"S", escopo:"int", grupo:"Vendas – Venda à Ordem",       desc:"Venda de mercadoria adquirida – entrega ao destinatário pelo remetente" },
  { codigo:"6.151", dir:"S", escopo:"int", grupo:"Transferências",               desc:"Transferência de produção entre estabelecimentos da mesma empresa" },
  { codigo:"6.152", dir:"S", escopo:"int", grupo:"Transferências",               desc:"Transferência de mercadoria entre estabelecimentos da mesma empresa" },
  { codigo:"6.201", dir:"S", escopo:"int", grupo:"Devoluções",                   desc:"Devolução de compra para industrialização" },
  { codigo:"6.202", dir:"S", escopo:"int", grupo:"Devoluções",                   desc:"Devolução de compra para comercialização" },
  { codigo:"6.251", dir:"S", escopo:"int", grupo:"Energia Elétrica",             desc:"Venda de energia elétrica para estabelecimento industrial" },
  { codigo:"6.252", dir:"S", escopo:"int", grupo:"Energia Elétrica",             desc:"Venda de energia elétrica para estabelecimento comercial" },
  { codigo:"6.301", dir:"S", escopo:"int", grupo:"Serviços",                     desc:"Prestação de serviço de comunicação" },
  { codigo:"6.401", dir:"S", escopo:"int", grupo:"Vendas – Subst. Tributária",   desc:"Venda de produção do estabelecimento – ST" },
  { codigo:"6.403", dir:"S", escopo:"int", grupo:"Vendas – Subst. Tributária",   desc:"Venda de mercadoria adquirida com ST já retida" },
  { codigo:"6.404", dir:"S", escopo:"int", grupo:"Vendas – Subst. Tributária",   desc:"Venda de mercadoria com ST cujo imposto já foi recolhido" },
  { codigo:"6.501", dir:"S", escopo:"int", grupo:"Depósito Fechado / Armazém",   desc:"Remessa de produção para armazém geral em outro estado" },
  { codigo:"6.502", dir:"S", escopo:"int", grupo:"Depósito Fechado / Armazém",   desc:"Remessa de mercadoria para armazém geral em outro estado" },
  { codigo:"6.551", dir:"S", escopo:"int", grupo:"Ativo Imobilizado",            desc:"Venda de bem do ativo imobilizado" },
  { codigo:"6.555", dir:"S", escopo:"int", grupo:"Brindes / Amostras",           desc:"Remessa de amostra grátis" },
  { codigo:"6.556", dir:"S", escopo:"int", grupo:"Brindes / Amostras",           desc:"Remessa de mercadoria em doação" },
  { codigo:"6.929", dir:"S", escopo:"int", grupo:"Outras",                       desc:"Lançamento de emissão de NF para operação também registrada em ECF" },
  { codigo:"6.933", dir:"S", escopo:"int", grupo:"Serviços – ISS",               desc:"Prestação de serviço tributado pelo ISSQN" },
  { codigo:"6.949", dir:"S", escopo:"int", grupo:"Outras",                       desc:"Outra saída de mercadoria ou prestação de serviço não especificada" },

  // ── SAÍDAS PARA O EXTERIOR ─────────────────────────────────────────────────
  { codigo:"7.101", dir:"S", escopo:"ext", grupo:"Exportação",                   desc:"Venda de produção do estabelecimento" },
  { codigo:"7.102", dir:"S", escopo:"ext", grupo:"Exportação",                   desc:"Venda de mercadoria adquirida para comercialização" },
  { codigo:"7.201", dir:"S", escopo:"ext", grupo:"Exportação – Devoluções",      desc:"Devolução de compra para industrialização" },
  { codigo:"7.202", dir:"S", escopo:"ext", grupo:"Exportação – Devoluções",      desc:"Devolução de compra para comercialização" },
  { codigo:"7.501", dir:"S", escopo:"ext", grupo:"Exportação",                   desc:"Exportação de mercadoria recebida com o fim específico de exportação" },
  { codigo:"7.551", dir:"S", escopo:"ext", grupo:"Exportação – Ativo",           desc:"Venda de bem do ativo imobilizado" },
];

// ─── CST ICMS (regime normal – Código de Situação Tributária) ────────────────
export const CST_ICMS = [
  { cst:"00", desc:"Tributada integralmente",                                                                   cor:"#22c55e" },
  { cst:"10", desc:"Tributada e com cobrança do ICMS por substituição tributária",                              cor:"#3b82f6" },
  { cst:"20", desc:"Com redução de base de cálculo",                                                            cor:"#f59e0b" },
  { cst:"30", desc:"Isenta ou não tributada e com cobrança do ICMS por substituição tributária",                cor:"#8b5cf6" },
  { cst:"40", desc:"Isenta",                                                                                     cor:"#06b6d4" },
  { cst:"41", desc:"Não tributada",                                                                             cor:"#64748b" },
  { cst:"50", desc:"Suspensão",                                                                                  cor:"#f97316" },
  { cst:"51", desc:"Diferimento",                                                                               cor:"#a78bfa" },
  { cst:"60", desc:"ICMS cobrado anteriormente por substituição tributária",                                    cor:"#ec4899" },
  { cst:"70", desc:"Com redução de base de cálculo e cobrança do ICMS por substituição tributária",             cor:"#f43f5e" },
  { cst:"90", desc:"Outras",                                                                                     cor:"#94a3b8" },
];

// ─── CSOSN – Simples Nacional ─────────────────────────────────────────────────
export const CSOSN_DATA = [
  { cst:"101", desc:"Tributada pelo Simples Nacional com permissão de crédito",                                   cor:"#22c55e" },
  { cst:"102", desc:"Tributada pelo Simples Nacional sem permissão de crédito",                                   cor:"#4ade80" },
  { cst:"103", desc:"Isenção do ICMS no Simples Nacional para faixa de receita bruta",                           cor:"#06b6d4" },
  { cst:"201", desc:"Tributada pelo Simples Nacional com permissão de crédito e com cobrança do ICMS por ST",     cor:"#3b82f6" },
  { cst:"202", desc:"Tributada pelo Simples Nacional sem permissão de crédito e com cobrança do ICMS por ST",     cor:"#60a5fa" },
  { cst:"203", desc:"Isenção do ICMS no Simples Nacional para faixa de receita bruta e com cobrança do ICMS por ST", cor:"#818cf8" },
  { cst:"300", desc:"Imune",                                                                                      cor:"#a78bfa" },
  { cst:"400", desc:"Não tributada pelo Simples Nacional",                                                        cor:"#64748b" },
  { cst:"500", desc:"ICMS cobrado anteriormente por ST ou por antecipação",                                      cor:"#f97316" },
  { cst:"900", desc:"Outros (quando não se enquadrar nos demais)",                                               cor:"#94a3b8" },
];

// ─── CST PIS/COFINS ──────────────────────────────────────────────────────────
export const CST_PIS_COFINS = [
  { cst:"01", tipo:"saída", desc:"Operação Tributável (base de cálculo = valor da operação alíquota normal – cumulativo/não-cumulativo)" },
  { cst:"02", tipo:"saída", desc:"Operação Tributável (base de cálculo = valor da operação – alíquota diferenciada)" },
  { cst:"03", tipo:"saída", desc:"Operação Tributável (base de cálculo = quantidade vendida × alíquota por unidade de produto)" },
  { cst:"04", tipo:"saída", desc:"Operação Tributável – Monofásica (alíquota zero)" },
  { cst:"05", tipo:"saída", desc:"Operação Tributável por ST" },
  { cst:"06", tipo:"saída", desc:"Operação Tributável (alíquota zero)" },
  { cst:"07", tipo:"saída", desc:"Operação Isenta da Contribuição" },
  { cst:"08", tipo:"saída", desc:"Operação sem Incidência da Contribuição" },
  { cst:"09", tipo:"saída", desc:"Operação com Suspensão da Contribuição" },
  { cst:"49", tipo:"saída", desc:"Outras Operações de Saída" },
  { cst:"50", tipo:"entrada", desc:"Operação com Direito a Crédito – Vinculada Exclusivamente a Receita Tributada no Mercado Interno" },
  { cst:"51", tipo:"entrada", desc:"Operação com Direito a Crédito – Vinculada Exclusivamente a Receita Não Tributada no Mercado Interno" },
  { cst:"52", tipo:"entrada", desc:"Operação com Direito a Crédito – Vinculada Exclusivamente a Receita de Exportação" },
  { cst:"53", tipo:"entrada", desc:"Operação com Direito a Crédito – Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno" },
  { cst:"54", tipo:"entrada", desc:"Operação com Direito a Crédito – Vinculada a Receitas Tributadas no Mercado Interno e de Exportação" },
  { cst:"55", tipo:"entrada", desc:"Operação com Direito a Crédito – Vinculada a Receitas Não-Tributadas no Mercado Interno e de Exportação" },
  { cst:"56", tipo:"entrada", desc:"Operação com Direito a Crédito – Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno e de Exportação" },
  { cst:"60", tipo:"entrada", desc:"Crédito Presumido – Operação de Aquisição Vinculada Exclusivamente a Receita Tributada no Mercado Interno" },
  { cst:"61", tipo:"entrada", desc:"Crédito Presumido – Operação de Aquisição Vinculada Exclusivamente a Receita Não-Tributada no Mercado Interno" },
  { cst:"62", tipo:"entrada", desc:"Crédito Presumido – Operação de Aquisição Vinculada Exclusivamente a Receita de Exportação" },
  { cst:"63", tipo:"entrada", desc:"Crédito Presumido – Vinculado a Receitas Tributadas e Não-Tributadas no Mercado Interno" },
  { cst:"64", tipo:"entrada", desc:"Crédito Presumido – Vinculado a Receitas Tributadas no Mercado Interno e de Exportação" },
  { cst:"65", tipo:"entrada", desc:"Crédito Presumido – Vinculado a Receitas Não-Tributadas no Mercado Interno e de Exportação" },
  { cst:"66", tipo:"entrada", desc:"Crédito Presumido – Vinculado a Receitas Tributadas e Não-Tributadas no Mercado Interno e de Exportação" },
  { cst:"67", tipo:"entrada", desc:"Crédito Presumido – Outras Origens" },
  { cst:"70", tipo:"entrada", desc:"Operação de Aquisição sem Direito a Crédito" },
  { cst:"71", tipo:"entrada", desc:"Operação de Aquisição com Isenção" },
  { cst:"72", tipo:"entrada", desc:"Operação de Aquisição com Suspensão" },
  { cst:"73", tipo:"entrada", desc:"Operação de Aquisição a Alíquota Zero" },
  { cst:"74", tipo:"entrada", desc:"Operação de Aquisição sem Incidência da Contribuição" },
  { cst:"75", tipo:"entrada", desc:"Operação de Aquisição por ST" },
  { cst:"98", tipo:"entrada", desc:"Outras Operações de Entrada" },
  { cst:"99", tipo:"saída",   desc:"Outras Operações" },
];

// ─── SINTEGRA / SEFAZ por estado ─────────────────────────────────────────────
export const SINTEGRA_ESTADOS = [
  { uf:"AC", nome:"Acre",           url:"https://www1.sefaznet.ac.gov.br/sintegra/", obs:"SINTEGRA-AC" },
  { uf:"AL", nome:"Alagoas",        url:"https://www.sefaz.al.gov.br/cgi-bin/sintegra/validacontribuinte.pl", obs:"Consulta contribuinte" },
  { uf:"AM", nome:"Amazonas",       url:"https://www.sefaz.am.gov.br/area.aspx?id=49", obs:"SINTEGRA-AM" },
  { uf:"AP", nome:"Amapá",          url:"https://sefaz.ap.gov.br/sefaznet2/index.jsf", obs:"Portal SEFAZ-AP" },
  { uf:"BA", nome:"Bahia",          url:"https://sistemas.sefaz.ba.gov.br/cadconfaz/", obs:"Cadastro de Contribuintes" },
  { uf:"CE", nome:"Ceará",          url:"https://cagef.sefaz.ce.gov.br/cagef/ConsultaCadastro.do", obs:"CAGEF – Contribuinte" },
  { uf:"DF", nome:"Distrito Federal",url:"https://sso.portalservicos.fazenda.df.gov.br/", obs:"Portal SEFAZ-DF" },
  { uf:"ES", nome:"Espírito Santo", url:"https://internet.sefaz.es.gov.br/infoContribuinte/", obs:"SINTEGRA-ES" },
  { uf:"GO", nome:"Goiás",          url:"https://www.sefaz.go.gov.br/sicoweb/", obs:"SINTEGRA-GO" },
  { uf:"MA", nome:"Maranhão",       url:"https://sistemas.sefaz.ma.gov.br/sintegra/", obs:"SINTEGRA-MA" },
  { uf:"MG", nome:"Minas Gerais",   url:"https://www.fazenda.mg.gov.br/empresas/consulta_cadastro_contribuintes/", obs:"Cadastro SEFAZ-MG" },
  { uf:"MS", nome:"Mato Grosso do Sul", url:"https://www.efazenda.ms.gov.br/sintegra/", obs:"SINTEGRA-MS" },
  { uf:"MT", nome:"Mato Grosso",    url:"https://www.sefaz.mt.gov.br/sintegra/", obs:"SINTEGRA-MT" },
  { uf:"PA", nome:"Pará",           url:"https://www.sefa.pa.gov.br/sintegra/", obs:"SINTEGRA-PA" },
  { uf:"PB", nome:"Paraíba",        url:"https://www.sefaz.pb.gov.br/sintegra/", obs:"SINTEGRA-PB" },
  { uf:"PE", nome:"Pernambuco",     url:"https://www.sefaz.pe.gov.br/sintegra/", obs:"SINTEGRA-PE" },
  { uf:"PI", nome:"Piauí",          url:"https://webas.sefaz.pi.gov.br/sintegra/", obs:"SINTEGRA-PI" },
  { uf:"PR", nome:"Paraná",         url:"https://www.fazenda.pr.gov.br/Modules/Tributos/CDEMP/", obs:"Cadastro SEFAZ-PR" },
  { uf:"RJ", nome:"Rio de Janeiro", url:"https://www.fazenda.rj.gov.br/sintegra/", obs:"SINTEGRA-RJ" },
  { uf:"RN", nome:"Rio Grande do Norte", url:"https://www.set.rn.gov.br/contentproducao/aplicacao/set_sintegra/consulta_livre/gerados/consulta_sintegra.asp", obs:"SINTEGRA-RN" },
  { uf:"RO", nome:"Rondônia",       url:"https://www.sefin.ro.gov.br/sintegra/", obs:"SINTEGRA-RO" },
  { uf:"RR", nome:"Roraima",        url:"https://www.sefaz.rr.gov.br/", obs:"Portal SEFAZ-RR" },
  { uf:"RS", nome:"Rio Grande do Sul", url:"https://www.sefaz.rs.gov.br/SINTEGRA/SINTEGRA-entry.aspx", obs:"SINTEGRA-RS" },
  { uf:"SC", nome:"Santa Catarina", url:"https://sat.sef.sc.gov.br/tax.NET/Sat.Sintegra.Web/Consultas/Contribuinte/Consulta.aspx", obs:"SINTEGRA-SC" },
  { uf:"SE", nome:"Sergipe",        url:"https://www.sefaz.se.gov.br/sintegra/", obs:"SINTEGRA-SE" },
  { uf:"SP", nome:"São Paulo",      url:"https://www.fazenda.sp.gov.br/cadweb/rest/cadastro/pages/index.html", obs:"CADESP – Cadastro SP" },
  { uf:"TO", nome:"Tocantins",      url:"https://sintegra.sefaz.to.gov.br/", obs:"SINTEGRA-TO" },
];
